### ISSUE TITLE
SecureClientIp causes 500 when x-forwarded-for is missing

### ISSUE THREAD

**Issue by 1oglop1** [imbolc/axum-client-ip#11]
I configured the server to expect x-forwarded-for `SecureClientIpSource::RightmostXForwardedFor` and the handler with `secure_ip: SecureClientIp`.

However, when the client does not send the header, the server returns 500. I'd expect 400 or another 4XX error. 

Am I missing anything? Is this an expected behaviour?

**Comment by imbolc** [comment]
Secure extractors are meant to be used when:
- you control the last proxy (e.g. you use Nginx on a vps) and so the issue is with your proxy configuration, not with the request
- or you're using some kind of a service (e.g. Flyio) for which, if the issue occured, it's again you who should fix it (e.g. read the service docs and use another extractor) not an issuer of the request

**Comment by imbolc** [comment]
Here's [an example](https://github.com/imbolc/axum-client-ip/blob/main/examples/secure.rs) using env variables to keep the IP source. You can just put `dotenv::dotenv()` on top of the main, and then using `.env` file. So locally it's content would be `IP_SOURCE=ConnectInfo` and on the server `IP_SOURCE=RightmostXForwardedFor`.

> PS. I'm struggling to find how to build the String or &str from In/SecureIp

`ip.0.to_string()`, but with Axum you usually extract the inner ip in the function signature: https://github.com/imbolc/axum-client-ip/blob/main/examples/secure.rs#L12

**Comment by imbolc** [comment]
`pub struct InsecureClientIp(pub IpAddr)` is a tuple containing `IpAddr` as a single member, so you can use `.0` or tuple destruction to extract it.

**Comment by 1oglop1** [comment]
> `IP_SOURCE=ConnectInfo` and on the server `IP_SOURCE=RightmostXForwardedFor`

Thanks a lot! 
I still cannot get used to this `SecureClientIp(ip): SecureClientIp` which unpacked the tuple for me. 

Alright, I did read the example, however, the codebase I'm trying to contribute to doesn't seem to be compatible with `envy` because we are using `clap`, so I'll need to wire it somehow together. But that's the problem for another day.

**Comment by imbolc** [comment]
Clap can parse env vars, just enable `env` feature:
```rust
#[arg(env)]
ip_source: SecureClientIpSource
```

**Comment by 1oglop1** [comment]
> Clap can parse env vars, just enable `env` feature:
> 
> ```rust
> #[arg(env)]
> ip_source: SecureClientIpSource
> ```

If I remember correctly the problem for me was setting the default value. Or converting the string `RightmostXForwardedFor` to an enum member. 
There isn't anything built-in clap I could find to simply point the enum `SecureClientIpSource` and pass the value via CLI.

My rust know very limited and anything that takes more than 10 minutes to figure out is out of the scope of my PoC. But I will take a look later again.

**Comment by imbolc** [comment]
Yep, I think `FromStr` is a good enough solution. Clap supports default values: https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#defaults

**Comment by 1oglop1** [comment]
> Yep, I think `FromStr` is a good enough solution. Clap supports default values: https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#defaults

I went back and checked what problem I had with `SecureClientIpSource` and found out that it seems a limitation of the language itself. Because `SecureClientIpSource` does not implement `FromString` and I cannot simply implement it for it myself without a wrapper. 

```
only traits defined in the current crate can be implemented for types defined outside of the crate
define and implement a trait or new type instead
```

So it looks like that any change required must be done here `axum-client-ip` eg. with use of https://docs.rs/strum/latest/strum/  and it's derive macros.

**Comment by imbolc** [comment]
Yep, you often encounter this issue with Rust, the natural solution is the [newtype pattern](https://doc.rust-lang.org/rust-by-example/generics/new_types.html).

Though it seems to be a common issue, so I'd accept a PR with a `FromStr` implementation. No additional dependencies though, it's already implements `Deserialize`, you an use it in the implementation.

**Comment by TheOrdinaryWow** [comment]
This seems to be broken in `V1`.

![Image](https://github.com/user-attachments/assets/1e07e9f8-5d71-4743-a8ba-ee987a79d97b)

**Comment by imbolc** [comment]
> This seems to be broken in `V1`.
> 
> ![Image](https://github.com/user-attachments/assets/1e07e9f8-5d71-4743-a8ba-ee987a79d97b)

I've just checked v0.7 and I don't see a Display implementation there, so your code shouldn't work there either. Just send a PR if you need it implemented.
